### PR TITLE
Remove native iOS tests

### PR DESCRIPTION
**Pull request by okwasniewski**
## Summary:

This PR removes native iOS tests as they are no longer used. 

Unfortunately, this change creates a big diff in `HelloWorld.xcodeproj/project.pbxproj` We should annotate it in upgrade helper. But less code to maintain for users is always better 👍🏻 

### Manual Instruction for upgrade helper 

1. Open the xcworkspace
2. Remove the target
3. Open the Podfile
4. Remove the section for the Tests
5. rerun pod install.

## Changelog:

[IOS] [REMOVED] - Native iOS tests

## Test Plan:

1. Create a new project
2. Test if there is no sign of native tests in Xcode
3. Build the app

### CODE REVIEW

**Comment by thymikee** [comment]
Can you add manual instructions of what needs to be changed in Xcode, so that it stays in this PR and can be easily referenced / copied over to the Upgrade Helper?

**Comment by okwasniewski** [comment]
@thymikee I've added additional instructions for manual steps in Xcode if users don't want to deal with editing the file manually

**Comment by cipolleschi** [comment]
Instructions could be simpler: it should be enough to:
1. Open the xcworkspace
2. Remove the target
3. Open the Podfile
4. Remove the section for the Tests
5. rerun `pod install`.

Step 5 should take care of all the other parts.

**Review by cipolleschi — APPROVED** [review]

**Comment by okwasniewski** [comment]
Thanks @cipolleschi, I upgraded the instructions

**Comment by okwasniewski** [comment]
Hey @cipolleschi is anything blocking the merge?

**Review by cipolleschi — APPROVED** [review]

**Comment by cipolleschi** [comment]
> Hey @cipolleschi is anything blocking the merge?

My (lack of) time! xD

**Pull request merged**
