### PR TITLE
feat: use react-native-safe-area-context

### PR DESCRIPTION
**Pull request by blakef**
We're recommending using [react-native-safe-area-context](https://github.com/th3rdwave/react-native-safe-area-context) instead of [SafeAreaView](https://reactnative.dev/docs/safeareaview) for Android 15 `targetSDK = 35`.

| With StatusBar | Without StatusBar |
| --------------- | ------------------ |
| e2e | e2e-hidden-status-bar |

### CODE REVIEW

**Comment by blakef** [comment]
CC @alanleedev

**Comment by blakef** [comment]
We can't land this change until we figure out a couple of things.  At the moment when I use the `react-native-safe-area-context` library, this doesn't work edge-to-edge:

## Baseline
CleanShot 2024-11-13 at 10 31 00@2x

## Using react-native-safe-area-context:
CleanShot 2024-11-12 at 21 13 15@2x

**Comment by blakef** [comment]
@alanleedev I've opened up th3rdwave/react-native-safe-area-context#552

**Comment by alanleedev** [comment]
Closing in favor of new approach: https://github.com/react-native-community/template/pull/85

**Pull request closed without merging**
