### PR TITLE
fix: indentation in `PrivacyInfo.xcprivacy`

### PR DESCRIPTION
**Pull request by szymonrybczak**
## Summary:

This PR adjusts the indentation in `PrivacyInfo.xcprivacy` to align with the default `pod install` format, helping to reduce noise in future diffs where pod install is often executed.

## Changelog:

[GENERAL] [FIXED] - Fix indentation inside `PrivacyInfo.xcprivacy`

## Test Plan:

n/a

### CODE REVIEW

**Comment by szymonrybczak** [comment]
cc @cipolleschi, as we spoke this should be backported to previous React Native versions that contains `PrivacyInfo.xcprivacy`, it's a minor thing so it doesn't need separate patch but it can wait for release branch.

**Review by blakef — APPROVED** [review]

**Comment by cortinico** [comment]
If we want this in 0.75, it should be picked in the `0.75-stable` branch

**Comment by szymonrybczak** [comment]
>  If we want this in 0.75, it should be picked in the 0.75-stable branch

Agree, for 0.74 [PR](https://github.com/facebook/react-native/pull/45089) is ready for review. Also we should backport this indentation fix for all versions that contains `PrivacyManifest.xcprivacy` and update Upgrade Helper generated templates with fixed indentation, because once we release e.g. 0.74.x, diff will presented in a Upgrade Helper 😅

Also there are some other changes after running `pod install` inside a `project.pbxproj` file that probably also should be upstream to affected templates. I think @cipolleschi is looking into them

**Comment by cortinico** [comment]
> and update Upgrade Helper generated templates with fixed indentation, because once we release e.g. 0.74.x, diff will presented in a Upgrade Helper

Should we instead update the upgrade-helper to ignore whitespace differences rather than having to distribute those PRs to every branch?

**Comment by szymonrybczak** [comment]
@cortinico but whenever there'll be a new patch release of `0.74.x` let's say it'll contain wrongly formatted `PrivacyManifest.xcprivacy` ;/

**Comment by cortinico** [comment]
> @cortinico but whenever there'll be a new patch release of `0.74.x` let's say it'll contain wrongly formatted `PrivacyManifest.xcprivacy` ;/

cc @cipolleschi @blakef as they had opinions on how to handle this

**Comment by blakef** [comment]
I spent a bit of time looking into this.  Tweaking the upgrade-helper UI to handle this isn't the right way to do it.  It's complex and I can't see a way to do it without ongoing maintenance.  @cortinico suggested tweaking the rn-diff-purge, and I think it's a far simpler fix.

If we update [these lines](https://github.com/react-native-community/rn-diff-purge/blob/master/scripts/new-release.sh#L116-L117) to use the `-w` argument for `git diff`, it changes the current diff to what we want:

```diff
diff --git a/RnDiffApp/Gemfile b/RnDiffApp/Gemfile
index 2a7ce357c5..8d72c37a80 100644
--- a/RnDiffApp/Gemfile
+++ b/RnDiffApp/Gemfile
@@ -3,6 +3,7 @@ source 'https://rubygems.org'
 # You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
 ruby ">= 2.6.10"
 
-# Exclude problematic versions of cocoapods and activesupport that causes build failures.
-gem 'cocoapods', '>= 1.13', '!= 1.15.0', '!= 1.15.1'
-gem 'activesupport', '>= 6.1.7.5', '!= 7.1.0'
+# Cocoapods 1.15 introduced a bug which break the build. We will remove the upper
+# bound in the template on Cocoapods with next React Native release.
+gem 'cocoapods', '>= 1.13', '< 1.15'
+gem 'activesupport', '>= 6.1.7.5', '< 7.1.0'
diff --git a/RnDiffApp/__tests__/App.test.tsx b/RnDiffApp/__tests__/App.test.tsx
index a26d1ec09a..9eac6fbc87 100644
--- a/RnDiffApp/__tests__/App.test.tsx
+++ b/RnDiffApp/__tests__/App.test.tsx
@@ -10,10 +10,8 @@ import App from '../App';
 import {it} from '@jest/globals';
 
 // Note: test renderer must be required after react-native.
-import ReactTestRenderer from 'react-test-renderer';
+import renderer from 'react-test-renderer';
 
-it('renders correctly', async () => {
-  await ReactTestRenderer.act(() => {
-    ReactTestRenderer.create(<App />);
-  });
+it('renders correctly', () => {
+  renderer.create(<App />);
 });
diff --git a/RnDiffApp/android/app/build.gradle b/RnDiffApp/android/app/build.gradle
index 7ce274303e..58f4e0382c 100644
--- a/RnDiffApp/android/app/build.gradle
+++ b/RnDiffApp/android/app/build.gradle
@@ -8,14 +8,14 @@ apply plugin: "com.facebook.react"
  */
 react {
     /* Folders */
-    //   The root of your project, i.e. where "package.json" lives. Default is '../..'
-    // root = file("../../")
-    //   The folder where the react-native NPM package is. Default is ../../node_modules/react-native
-    // reactNativeDir = file("../../node_modules/react-native")
-    //   The folder where the react-native Codegen package is. Default is ../../node_modules/@react-native/codegen
-    // codegenDir = file("../../node_modules/@react-native/codegen")
-    //   The cli.js file which is the React Native CLI entrypoint. Default is ../../node_modules/react-native/cli.js
-    // cliFile = file("../../node_modules/react-native/cli.js")
+    //   The root of your project, i.e. where "package.json" lives. Default is '..'
+    // root = file("../")
+    //   The folder where the react-native NPM package is. Default is ../node_modules/react-native
+    // reactNativeDir = file("../node_modules/react-native")
+    //   The folder where the react-native Codegen package is. Default is ../node_modules/@react-native/codegen
+    // codegenDir = file("../node_modules/@react-native/codegen")
+    //   The cli.js file which is the React Native CLI entrypoint. Default is ../node_modules/react-native/cli.js
+    // cliFile = file("../node_modules/react-native/cli.js")
 
     /* Variants */
     //   The list of variants to that are debuggable. For those we're going to
@@ -49,9 +49,6 @@ react {
     //
     //   The list of flags to pass to the Hermes compiler. By default is "-O", "-output-source-map"
     // hermesFlags = ["-O", "-output-source-map"]
-
-    /* Autolinking */
-    autolinkLibrariesWithApp()
 }
 
 /**
@@ -117,3 +114,5 @@ dependencies {
         implementation jscFlavor
     }
 }
+
+apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)
diff --git a/RnDiffApp/android/app/src/main/AndroidManifest.xml b/RnDiffApp/android/app/src/main/AndroidManifest.xml
index e1892528b8..4122f36a59 100644
--- a/RnDiffApp/android/app/src/main/AndroidManifest.xml
+++ b/RnDiffApp/android/app/src/main/AndroidManifest.xml
@@ -8,8 +8,7 @@
       android:icon="@mipmap/ic_launcher"
       android:roundIcon="@mipmap/ic_launcher_round"
       android:allowBackup="false"
-      android:theme="@style/AppTheme"
-      android:supportsRtl="true">
+      android:theme="@style/AppTheme">
       <activity
         android:name=".MainActivity"
         android:label="@string/app_name"
diff --git a/RnDiffApp/android/build.gradle b/RnDiffApp/android/build.gradle
index df1ce4db3b..f536a79201 100644
--- a/RnDiffApp/android/build.gradle
+++ b/RnDiffApp/android/build.gradle
@@ -5,7 +5,7 @@ buildscript {
         compileSdkVersion = 34
         targetSdkVersion = 34
         ndkVersion = "26.1.10909125"
-        kotlinVersion = "1.9.24"
+        kotlinVersion = "1.9.22"
     }
     repositories {
         google()
diff --git a/RnDiffApp/android/gradle.properties b/RnDiffApp/android/gradle.properties
index 9fb15664bd..a46a5b90fa 100644
--- a/RnDiffApp/android/gradle.properties
+++ b/RnDiffApp/android/gradle.properties
@@ -21,6 +21,8 @@ org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m
 # Android operating system, and which are packaged with your app's APK
 # https://developer.android.com/topic/libraries/support-library/androidx-rn
 android.useAndroidX=true
+# Automatically convert third-party libraries to use AndroidX
+android.enableJetifier=true
 
 # Use this property to specify which architecture you want to build.
 # You can also override it from the CLI using
diff --git a/RnDiffApp/android/gradle/wrapper/gradle-wrapper.jar b/RnDiffApp/android/gradle/wrapper/gradle-wrapper.jar
index e6441136f3d4ba8a0da8d277868979cfbc8ad796..7f93135c49b765f8051ef9d0a6055ff8e46073d8 100644
GIT binary patch
<Redacted>

diff --git a/RnDiffApp/android/gradle/wrapper/gradle-wrapper.properties b/RnDiffApp/android/gradle/wrapper/gradle-wrapper.properties
index 6f7a6eb33e..2ea3535dc0 100644
--- a/RnDiffApp/android/gradle/wrapper/gradle-wrapper.properties
+++ b/RnDiffApp/android/gradle/wrapper/gradle-wrapper.properties
@@ -1,6 +1,6 @@
 distributionBase=GRADLE_USER_HOME
 distributionPath=wrapper/dists
-distributionUrl=https\://services.gradle.org/distributions/gradle-8.8-all.zip
+distributionUrl=https\://services.gradle.org/distributions/gradle-8.6-all.zip
 networkTimeout=10000
 validateDistributionUrl=true
 zipStoreBase=GRADLE_USER_HOME
diff --git a/RnDiffApp/android/gradlew b/RnDiffApp/android/gradlew
index b740cf1339..1aa94a4269 100755
--- a/RnDiffApp/android/gradlew
+++ b/RnDiffApp/android/gradlew
@@ -55,7 +55,7 @@
 #       Darwin, MinGW, and NonStop.
 #
 #   (3) This script is generated from the Groovy template
-#       https://github.com/gradle/gradle/blob/HEAD/platforms/jvm/plugins-application/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt
+#       https://github.com/gradle/gradle/blob/HEAD/subprojects/plugins/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt
 #       within the Gradle project.
 #
 #       You can find Gradle at https://github.com/gradle/gradle/.
diff --git a/RnDiffApp/android/settings.gradle b/RnDiffApp/android/settings.gradle
index 41b6e2a81f..e5f65b56c5 100644
--- a/RnDiffApp/android/settings.gradle
+++ b/RnDiffApp/android/settings.gradle
@@ -1,6 +1,4 @@
-pluginManagement { includeBuild("../node_modules/@react-native/gradle-plugin") }
-plugins { id("com.facebook.react.settings") }
-extensions.configure(com.facebook.react.ReactSettingsExtension){ ex -> ex.autolinkLibrariesFromCommand() }
 rootProject.name = 'RnDiffApp'
+apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
 include ':app'
 includeBuild('../node_modules/@react-native/gradle-plugin')
diff --git a/RnDiffApp/ios/RnDiffApp/PrivacyInfo.xcprivacy b/RnDiffApp/ios/RnDiffApp/PrivacyInfo.xcprivacy
index 41b8317f06..ef1896e70c 100644
--- a/RnDiffApp/ios/RnDiffApp/PrivacyInfo.xcprivacy
+++ b/RnDiffApp/ios/RnDiffApp/PrivacyInfo.xcprivacy
@@ -2,6 +2,9 @@
 <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
 <plist version="1.0">
 <dict>
+  <key>NSPrivacyCollectedDataTypes</key>
+  <array>
+  </array>
   <key>NSPrivacyAccessedAPITypes</key>
   <array>
     <dict>
@@ -29,8 +32,6 @@
       </array>
     </dict>
   </array>
-	<key>NSPrivacyCollectedDataTypes</key>
-	<array/>
   <key>NSPrivacyTracking</key>
   <false/>
 </dict>
diff --git a/RnDiffApp/package.json b/RnDiffApp/package.json
index dafa270141..40380022b8 100644
--- a/RnDiffApp/package.json
+++ b/RnDiffApp/package.json
@@ -10,24 +10,24 @@
     "test": "jest"
   },
   "dependencies": {
-    "react": "19.0.0-rc-fb9a90fa48-20240614",
-    "react-native": "0.75.0-rc.2"
+    "react": "18.2.0",
+    "react-native": "0.74.2"
   },
   "devDependencies": {
     "@babel/core": "^7.20.0",
     "@babel/preset-env": "^7.20.0",
     "@babel/runtime": "^7.20.0",
-    "@react-native/babel-preset": "0.75.0-rc.2",
-    "@react-native/eslint-config": "0.75.0-rc.2",
-    "@react-native/metro-config": "0.75.0-rc.2",
-    "@react-native/typescript-config": "0.75.0-rc.2",
+    "@react-native/babel-preset": "0.74.84",
+    "@react-native/eslint-config": "0.74.84",
+    "@react-native/metro-config": "0.74.84",
+    "@react-native/typescript-config": "0.74.84",
     "@types/react": "^18.2.6",
     "@types/react-test-renderer": "^18.0.0",
     "babel-jest": "^29.6.3",
     "eslint": "^8.19.0",
     "jest": "^29.6.3",
     "prettier": "2.8.8",
-    "react-test-renderer": "19.0.0-rc-fb9a90fa48-20240614",
+    "react-test-renderer": "18.2.0",
     "typescript": "5.0.4"
   },
   "engines": {

```

**Comment by szymonrybczak** [comment]
Oh, actually `-w` parameter would solve a bunch of issues! Nice find @blakef!

**Pull request merged**
